=== api-evangelist/amazon-application-discovery-service/json-schema/application-discovery-service-export-info-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/amazon-application-discovery-service/refs/heads/main/json-schema/application-discovery-service-export-info-schema.json",
  "title": "ExportInfo",
  "description": "ExportInfo schema from Amazon Application Discovery Service API",
  "type": "object",
  "properties": {
    "exportId": {
      "type": "string",
      "example": "export-500123",
      "description": "A unique identifier used to query the status of an export request."
    },
    "exportStatus": {
      "type": "string",
      "enum": [
        "FAILED",
        "SUCCEEDED",
        "IN_PROGRESS"
      ],
      "example": "SUCCEEDED",
      "description": "The status of the data export job."
    },
    "statusMessage": {
      "type": "string",
      "example": "Export complete",
      "description": "A status message provided for API callers."
    },
    "configurationsDownloadUrl": {
      "type": "string",
      "example": "https://s3.amazonaws.com/aws-application-discovery-service-export/500123/export.zip",
      "description": "A URL for an Amazon S3 bucket where you can review the exported data."
    },
    "exportRequestTime": {
      "type": "string",
      "example": "2026-04-19T10:00:00Z",
      "description": "The time that the data export was initiated."
    },
    "isTruncated": {
      "type": "boolean",
      "example": false,
      "description": "If true, the export of agent information exceeded the size limit for a single export, and the exported data is incomplete."
    },
    "requestedStartTime": {
      "type": "string",
      "example": "2026-04-01T00:00:00Z",
      "description": "The value of startTime parameter in the StartExportTask request."
    },
    "requestedEndTime": {
      "type": "string",
      "example": "2026-04-19T23:59:59Z",
      "description": "The endTime used in the StartExportTask request. If no endTime was requested, this result does not appear in ExportInfo."
    }
  },
  "required": [
    "exportId",
    "exportStatus",
    "statusMessage",
    "exportRequestTime"
  ]
}

=== api-evangelist/amazon-application-discovery-service/examples/application-discovery-service-export-info-example.json
{
  "exportId": "export-500123",
  "exportStatus": "SUCCEEDED",
  "statusMessage": "Export complete",
  "configurationsDownloadUrl": "https://s3.amazonaws.com/aws-application-discovery-service-export/500123/export.zip",
  "exportRequestTime": "2026-04-19T10:00:00Z",
  "isTruncated": false,
  "requestedStartTime": "2026-04-01T00:00:00Z",
  "requestedEndTime": "2026-04-19T23:59:59Z"
}
